### PR TITLE
Switch to external bits helm sub-chart

### PR DESCRIPTION
**Pull request by kiranjain2**
In order to separate concerns for helm charts the sub-chart for `bits` have been moved to `bits-service-release` project and are now referenced in Eirini via helm dependency.

#164273622

### CODE REVIEW

**Comment by gdankov** [comment]
Hi @kiranjain2,

Can you please resolve the merge conflicts so we can merge the PR?

**Comment by kiranjain2** [comment]
@gdankov I resolved the conflicts

**Comment by gdankov** [comment]
Thanks, @kiranjain2.

One more thing -- installing the bits' chart returns an error related to the location of `restartPolicy` in the template.

Can you please take a look at https://github.com/cloudfoundry-incubator/bits-service-release/pull/26

Best regards,
Georgi

**Comment by petergtz** [comment]
Hey @gdankov, we've merged https://github.com/cloudfoundry-incubator/bits-service-release/pull/26. It's available in the bits helm chart as version 0.1.0-dev.

**Comment by petergtz** [comment]
@gdankov I've resolved the conflicts in this PR. Could you please have a look? Thanks.

**Comment by alex-slynko** [comment]
@petergtz @kiranjain2 
I run it in our CI. The story is close to the top of our backlog.

**Comment by alex-slynko** [comment]
@petergtz @kiranjain2 
We will investigate [overriding values in subchart](https://helm.sh/docs/chart_template_guide/#overriding-values-of-a-child-chart) before merging your PR.  I don't want users to specify the same value multiple times in different places.
Right now they will have to specify `rootfs_tag` twice(for `rootfs_patcher` and `bits`) and `kube.external_ips` three times.

**Comment by gdankov** [comment]
Thanks, @kiranjain2 @petergtz

Sorry for taking that long to merge this, we had some CI issues that we wanted to fix first.

Kind regards,
Georgi && @JulzDiverse

**Pull request merged**
