### PR TITLE
Use Ingress Endpoint in Bits Service Charts

### PR DESCRIPTION
**Pull request by tareqmamari**
- Use Registry Ingress Endpoint for bits-service's public endpoint if `use_registry_ingress` is set, same as in `configmap.yaml`

### CODE REVIEW

**Comment by tareqmamari** [comment]
@petergtz the double quotes are added as a minor change to maintain the consistency with what we have in the eirini pod config file. In conclusion, they are not really needed.

We need to hold merging the PR till we figure out the reason behind the `403`s which we receive from the `bits-service`. Other than that, the updates introduced by this PR could set the bits registry ingress correctly, and we tested that, where the requests to the bits-service process are received successfully through the bits-registry ingress, but we still need to know why we are getting these `403`s.

**Comment by petergtz** [comment]
Please separate cosmetic changes from functional changes, i.e. please
remove the double quotes. Specifically, because they're not used
consistently in the other yamls and they're not necessary for valid yaml.
So in the end this adds noise to the change *and* the yaml in general. I
know this sounds like nit-picking, but it's really annoying whenever you do
a git blame in the future.

Tareq Al-Maamari <notifications@github.com> schrieb am Mi., 27. Feb. 2019,
21:22:

**Comment by tareqmamari** [comment]
@petergtz we will update the PR shortly as soon as the bits new release is out (including the new names for the registry endpoint).

@HeavyWombat FYI

**Comment by tareqmamari** [comment]
Obsolete as the changes are included here: https://github.com/cloudfoundry-incubator/eirini-release/pull/42

**Pull request closed without merging**
